name: CI/CD Pipeline

on:

  push:
      branches:
        - develop
        
  pull_request:
    branches:
      - develop

jobs:
#Para el formato del codigo
  format:
    name: Formato de codigo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'


      - name: Install dependencies
        run: npm install


      - name: Check code formatting
        run: npm run format:check

#Para los test
  test:
    name: Pruebas unitarias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'


      - name: Install dependencies
        run: npm install


      - name: Run unit tests

        run: npm run test


  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'


      - name: Install dependencies
        run: npm install


      - name: Run integration tests
        run: npm run test:integration

#Garantiza que el codigo cumple con buenas practicas
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Cambia según la versión que uses


      - name: Install dependencies
        run: npm install


      - name: Run linter
        run: npm run lint

#Parte donde se simula la build del proyecto
  build:
    name: Build proyecto
    runs-on: ubuntu-latest
    #Esta parte te pide las anteriores, de lo contrario no se construye nada
    needs: [format, test, integration-tests,lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    #Condicionamos a que el merge sea ok en la rama develop
    if: github.ref == 'refs/heads/develop' && github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Firebase CLI
        uses: w9jds/firebase-action@v1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
